GitHub Action: move from Oracle Java to Microsoft OpenJDK
Try to move to Java 9, which Matteo has tested thoroughly. Java 17, the
minimum version we can get with Oracle's action, gives errors:

——————————————————————————————————————————————————————————————————————————————————————————————————
Error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.verapdf.apps.Applications.createConfigManager(Applications.java:75)
	at org.verapdf.apps.Applications.createAppConfigManager(Applications.java:87)
	at org.verapdf.cli.VeraPdfCli.<clinit>(VeraPdfCli.java:46)
	at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:34)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
——————————————————————————————————————————————————————————————————————————————————————————————————