GitHub Action: add PDF/A conversion and validation
• Conversion is achieved by parsing and rebuilding through ghostscript
• Validation is done using veraPDF

All packed together in a nice script, which we retrieve from
> https://github.com/matteosecli/pdf2archive

To be tested: I'm especially worried about Java runtime…

GitHub Action: add manual trigger to PDF/A workflow

For easier debugging, we have a weird path problem.

GitHub Action: debug PDF/A workflow

Added a ls -lha command since, as weird as it sounds, I get:

————————————————————————————————————————————————————————————————————————
$ ./pdf2archive [options] latex.pdf esse3.pdf

shell: /usr/bin/bash -e {0}

/home/runner/work/_temp/eb36ff5f-6573-4ce6-be20-19614d483367.sh: line 1:
./pdf2archive: Is a directory
————————————————————————————————————————————————————————————————————————

GitHub Action: debug PDF/A workflow [sgrunt]

I did some tests in local:

• Title and Keywords were missing, probably problems with "à" character

• If I call ./pdf2archive with no input I get a very suspicious
  > zsh: no such file or directory: ./pdfarchive

So I'd try changing the multiline option from ">-" to ">" (despite not
really convinced) and remove "à" in favor of "a'". Let's see…

GitHub Action: let's try with a single line command [mah]

GitHub Action: revert commit 3221806fcb0ef579b9c9fa41c2585041003f15ad

Same problem... so what the heck is going on? Let's try using explicit
sh command syntax (it behaves slightly different locally, namely it runs
and shows the help if no input name is provided).

> I hate GitHub actions, truly, deeply.

GitHub Action: change to explicit sh command also at validation step

It was that... what the heck. Of course I forgot I call pdf2archive again later…

Time to see what happens with veraPDF :)

GitHub Actions: speaking of path problems... [double sgrunt]

$ sh pdf2archive --validate-only

  JAVA_HOME: /opt/hostedtoolcache/Java_jdkfile_jdk/17/x64

$ mv esse3.pdf ../output/esse3.pdf

  mv: cannot stat 'esse3.pdf': No such file or directory
  Process completed with exit code 1.

So... let's add again a "ls -lha" command and see what's the deal now...
Since veraPDF seems way too silent, let's also add a --debug flag.

GitHub Action: setup-java action apparently resets current directory ☠️

> I hate GitHub actions, truly, deeply... DID I SAY THIS ALREADY?!

GitHub Action: sh did not solve nothing, esse3.pdf is missing

I also did some local test: 6c5d17b37eae6df4379f680e79c0fcac00807741 did
not provide a solution!

Apparently if I run "sh pdf2archive [...]" I DO NOT get an error, but
neither I get the conversion done… 😩

NOTES)

• This why everything was so silent…
• Let's remove chmod command, as apparently is not needed by sh command…

GitHub Action: I do not now what to try anymore…

> reset chmod permissions and then give them again…

GitHub Actions: chmod apparently does not work on the runner

From bash manual:

If a command is found but is not executable, the return status is 126.
> https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

From the damn action log:

./pdf2archive: Is a directory
Error: Process completed with exit code 126.

So, despite the message being "is a directory" the actual problem is
that the file is not executable. Fuck.

NOTE) The thing must be very subtle, since previously we got
      -rwxr-xr-x 1 runner docker  16K Jun 15 00:50 pdf2archive
      from a ls -lh command. WTF.

      > let's try with chmode a+rx

GitHub Action: test random stuff 🤢

GitHub Action: change to explicit BASH command also at validation step

Let's retry the strategy of commit 6c5d17b37eae6df4379f680e79c0fcac00807741,
but using bash instead of sh.

> a local test gives some hope…

GitHub Action: simpler test

Revert "GitHub Action: simpler test"

This reverts commit c391306d1ebcc09687ffec7fa3742632999c4358.

GitHub Action: try downgrading ubuntu

The error seems to weird to me, let's try changing ubuntu version.

 #hopeless

Revert "GitHub Action: try downgrading ubuntu"

This reverts commit 49e992a25df35e9fcd81f1a8584ebe3366d6cbba.

GitHub Action: whatever

GitHub Action: treat it again as a current directory problem

$ bash pdf2archive.sh --title="Valutazione infermieristica della qualita' della sedazione procedurale pediatrica" --subject="Nursing assessment of the quality of pediatric procedural sedation" --keywords="sedazione procedurale, pediatria, risveglio, qualita' del risveglio" --author="Anais Trinca" latex.pdf esse3.pdf

bash: pdf2archive.sh: No such file or directory

Error: Process completed with exit code 127.

> Interesting, maybe it's really a path problem?

GitHub Action: thoroughly investigate working tree structure

We solved the issue with calling pdf2archive, but now it has a weird
issue not finding veraPDF. I'm tired of these path problems, come on.

$ bash pdf2archive/pdf2archive.sh --validate-only
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_jdkfile_jdk/17/x64
  Validating...
  pdf2archive/pdf2archive.sh: line 122: ./verapdf/verapdf: No such file or directory

GitHub Action: rationalization of path handling

————————————————————————————————————————————————————————————————————————

  $ pwd
  $ ls -la

  /home/runner/work/trincatesi/trincatesi
  total 16
  drwxr-xr-x 4 runner docker 4096 Jun 15 04:23 .
  drwxr-xr-x 3 runner docker 4096 Jun 15 04:23 ..
  drwxr-xr-x 2 runner docker 4096 Jun 15 04:23 latex-build
  drwxr-xr-x 4 runner docker 4096 Jun 15 04:23 pdf2archive

  $ mv latex-build/draft.pdf pdf2archive/latex.pdf
  $ cd pdf2archive/   <------------ HERE WE ENTER SUCCESFULLY
  $ mv pdf2archive pdf2archive.sh

  $ bash pdf2archive/pdf2archive.sh [...] pdf2archive/latex.pdf pdf2archive/esse3.pdf

  >> WORKS PERFECTLY, WTF, AS IF PATH HAS BEEN RESET

  [...]

  $ bash pdf2archive/pdf2archive.sh --validate-only

  Validating...
  pdf2archive/pdf2archive.sh: line 122: ./verapdf/verapdf: No such file or directory

  [...]

  $ pwd
  $ ls -la

  /home/runner/work/trincatesi/trincatesi <---- HERE WE ARE AGAIN OUT!
  total 16
  drwxr-xr-x 4 runner docker 4096 Jun 15 04:23 .
  drwxr-xr-x 3 runner docker 4096 Jun 15 04:23 ..
  drwxr-xr-x 2 runner docker 4096 Jun 15 04:23 latex-build
  drwxr-xr-x 4 runner docker 4096 Jun 15 04:23 pdf2archive

>> IT SEEMS LIKE EVERYTIME WE INVOKE THE RUN COMMAND THE SHELL CURRENT
   DIRECTORY DOES RESET... WTF!

————————————————————————————————————————————————————————————————————————

So we fix it by performing the needed cd pdf2archive commands at each
step (so giving up yaml ">" multiline option and falling back to native
bash "\" line continuation syntax).

GitHub Action: move from Oracle Java to Microsoft OpenJDK

Try to move to Java 9, which Matteo has tested thoroughly. Java 17, the
minimum version we can get with Oracle's action, gives errors:

——————————————————————————————————————————————————————————————————————————————————————————————————
Error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.verapdf.apps.Applications.createConfigManager(Applications.java:75)
	at org.verapdf.apps.Applications.createAppConfigManager(Applications.java:87)
	at org.verapdf.cli.VeraPdfCli.<clinit>(VeraPdfCli.java:46)
	at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:34)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
——————————————————————————————————————————————————————————————————————————————————————————————————

GitHub Action: there is no available Java 9 action

Let's try with v11 before giving up on validation...

GitHub Action: revert Java version, update veraPDF instead

This reverts commits:
• 8cd1b4460ac22921753ff22332d7461b57af5ec5
• 194f2dbafddb2ad5ab9ae367625ff060e178b2c5

Following advice in https://github.com/matteosecli/pdf2archive/issues/15

GitHub Action: try not giving the path to veraPDF installer...

...and see what it says.

GitHub Action: give up updated veraPDF, try with corretto OpenJDK 8

veraPDF installer is inevitably interactive (or so it seems).

Amazon corretto provides Java 8. Version 9 is unachievable, for it was
not a LTS release. This needs to be the last try with validation.

GitHub Action: Java 8 appears to work, now give veraPDF the actual file

Dumb me… 💆🏻‍♂️

GitHub Action: add --debug option to veraPDF

GitHub Action: PDF2ARCHIVE doesn't implement debug mode in veraPDF calls

So we fall back to directly pass --passed and --verbose flags.